version: "3"

services:
  node-fullcycle:
    build:
      context: ./
    container_name: node-fullcycle
    entrypoint: dockerize -wait tcp://mysql-fullcycle:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "yarn && yarn build"
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql-fullcycle

  mysql-fullcycle:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-fullcycle
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx-fullcycle:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx-fullcycle
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node-fullcycle

networks:
  node-network:
    driver: bridge
